name: HTML Tests

on:
  pull_request:
    paths:
      - '**/*.html'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Git Repository
      uses: actions/checkout@v2

    - name: Install HTMLHint
      run: npm install htmlhint --global

    - name: HTML Tests In Process
      run: htmlhint '**/*.html'
